import courses from "./courses.json";
import course_menu from './course_menu.json';
import modules from "./modules.json";
import assignments from './assignments.json';
import users from './users.json';
import grades from './grades.json';
import enrollment from './enrollment.json';
import account_menu from './account_menu.json';
import accounts from './accounts.json';
export default {  courses, course_menu, modules, assignments, users,grades, enrollment, account_menu ,accounts};